### PR TITLE
Use "Github Actions" instead of AppVeyor

### PR DESCRIPTION
**Pull request by donid**
Since GitHub now supports automated builds, we do not need to use AppVeyor anymore.
This would make https://github.com/mwinapi/mwinapi/commit/a1e1d1a8bc428607b8d50e5ea21db41eae2de6e4#commitcomment-42749335 obsolete.

### CODE REVIEW

**Comment by donid** [comment]
we could also  provide build-artifacts as we did in AppVeyor and we should update the badge in the readme file...

**Comment by schierlm** [comment]
I changed the workflow to run on all branches. Running it only on master is IMHO too late. If we want some actions like build artifacts only on master (or excluding forks), we can limit that in the workflow as well.

    if: github.ref == 'refs/heads/master' && github.repository == 'mwinapi/mwinapi'

Feel free to add artifacts and/or change the badges. As I never used AppVeyor, I don't know what artifacts it usually builds.

**Comment by donid** [comment]
> I changed the workflow to run on all branches. Running it only on master is IMHO too late.

I am a newbie in GitHub actions and that was the default that was generated :-}

Here is the code that I used in AppVeyor to define artifacts (I guess it was me, because that was 5 years ago ;-) )

>artifacts:
>- path: ManagedWinapi\bin\Debug\
>  name: bin_Debug
>- path: ManagedWinapi\bin\ReleaseSigned\
>  name: bin_ReleaseSigned

**Comment by schierlm** [comment]
Heh. I have some experience with GitHub actions, but not for Windows builds.

**Comment by donid** [comment]
I have updated the badge and noticed that the workflow/action is named 'CI' - not the most descriptive name, but I am too tired to come up with a better one.
And a second issue: does the badge still point to my fork, when you merge the PR?

**Comment by schierlm** [comment]
I'll have to fix the link when merging. I'll also have to rebase and squash all my commits.

`https://github.com/mwinapi/mwinapi/workflows/Automated%20Build/badge.svg`

Do the artifacts look good now?

**Comment by schierlm** [comment]
BTW sorry that I force-pushed your master branch...

**Comment by schierlm** [comment]
sorry² that I introduced a typo in the link. And now as it is merged I can no longer push to your master branch. So will force-push the correct link to my master branch now :)

**Comment by donid** [comment]
> that I force-pushed your master branch...

No worries - the fork was only created for this PR, will be deleted soon

> Do the artifacts look good now?

zip-content looks good, but relative paths seem to work on Windows too and are better to read ;-)
> path: ManagedWinapi\bin\Debug\

**Comment by schierlm** [comment]
> zip-content looks good, but relative paths seem to work on Windows too and are better to read ;-)
> 
> > path: ManagedWinapi\bin\Debug\

Hmm, I tried it here https://github.com/donid/mwinapi/commit/f5d286b3bc5912ad346a7bff5f857937240b6e15  and it did not work https://github.com/donid/mwinapi/runs/1170889376.

Having a closer look now, it would have worked if I had built all the artifacts before... (only ReleaseSigned failed). Probably I was already too tired yesterday evening so I did not notice.

So if you prefer, feel free to send another pull request :)

**Pull request merged**
