### PR TITLE
migrate to vs2022

### PR DESCRIPTION
**Pull request by liziyu0714**

### CODE REVIEW

**Review by schierlm — CHANGES_REQUESTED** [review]
Hello,

thank you for your contributions.

Please do not commit all the `Backup` files, which are mostly identical to the files in the main folder (Except project and solution files)

You may have noticed that the project already contains two sets of project/solution files, one for VS 2008 and one for VS2010.

Therefore I'd like to ask you to do the same for your pull request. Either rename the original `ManagedWinapi.sln` and `ManagedWinapi.csproj` to `ManagedWinapi-2008.*` and update the existing files with your changes, or rename your new `.sln` and `.csproj` files to `*-2022.*`. In both cases, be aware that you need to edit the renamed `.sln` file with a text editor and change the path/filename to the `.csproj` file so that the file is still functional.

Thanks,

Michael

**Comment by schierlm** [comment]
For info, I added a third solution file to be used with GitHub actions (which uses VS2010 build file but .NET Framework 4.8.1). Therefore, you may want to rebase your branch (or I will do it before merging).

**Comment by liziyu0714** [comment]
Visual studio reports that I need to migrate all solution files and some of code file if I want to migrate to vs 2022;
As a result , you will be not able to build in vs2010 any more.
What should I do?

**Comment by liziyu0714** [comment]
Visual studio reports that I need to migrate all solution files and some of code file if I want to migrate to vs 2022;
As a result , you will be not able to build in vs2010 any more.
What should I do?
________________________________
发件人: Michael Schierl ***@***.***>
发送时间: 2024年7月27日 5:34
收件人: mwinapi/mwinapi ***@***.***>
抄送: liziyu0714 ***@***.***>; Author ***@***.***>
主题: Re: [mwinapi/mwinapi] migrate to vs2022 (PR #12)


For info, I added a third solution file to be used with GitHub actions (which uses VS2010 build file but .NET Framework 4.8.1). Therefore, you may want to rebase your branch (or I will do it before merging).

―

**Comment by schierlm** [comment]
> Visual studio reports that I need to migrate all solution files and some of code file if I want to migrate to vs 2022;
> As a result , you will be not able to build in vs2010 any more.

Do not believe what VS says. Your previous commit did not change any source code files, only the solution and project files.

In case it would be needed, we'd either need to split these files or try to keep the old version alive in a branch..

By the way, VS2010 is not the issue, VS2008 is. Between VS2008 and VS2010 Microsoft changed the EULA of the Community edition, making it impossible for large companies to use it for certain use cases, even if the company is not in the software business at all but for example produces groceries and only needs some inhouse tools to e.g handle payroll or HR automation. Those tend to still use VS2008 for that reason (even if the company makes big money, there might not be any money available for licensing software that is not necessarily needed).

**Pull request closed without merging**
